var namespacegams_1_1pose =
[
    [ "detail", "dd/df7/namespacegams_1_1pose_1_1detail.html", "dd/df7/namespacegams_1_1pose_1_1detail" ],
    [ "euler", "d3/d83/namespacegams_1_1pose_1_1euler.html", "d3/d83/namespacegams_1_1pose_1_1euler" ],
    [ "geodetic_util", "d7/d68/namespacegams_1_1pose_1_1geodetic__util.html", "d7/d68/namespacegams_1_1pose_1_1geodetic__util" ],
    [ "order", "d6/dcb/namespacegams_1_1pose_1_1order.html", "d6/dcb/namespacegams_1_1pose_1_1order" ],
    [ "Acceleration", "d8/d9b/classgams_1_1pose_1_1Acceleration.html", "d8/d9b/classgams_1_1pose_1_1Acceleration" ],
    [ "Angular", "d4/d1d/classgams_1_1pose_1_1Angular.html", "d4/d1d/classgams_1_1pose_1_1Angular" ],
    [ "AngularAcceleration", "dc/d8c/classgams_1_1pose_1_1AngularAcceleration.html", "dc/d8c/classgams_1_1pose_1_1AngularAcceleration" ],
    [ "AngularVector", "d0/d6b/classgams_1_1pose_1_1AngularVector.html", "d0/d6b/classgams_1_1pose_1_1AngularVector" ],
    [ "AngularVelocity", "d7/d98/classgams_1_1pose_1_1AngularVelocity.html", "d7/d98/classgams_1_1pose_1_1AngularVelocity" ],
    [ "Coordinate", "d6/dcb/classgams_1_1pose_1_1Coordinate.html", "d6/dcb/classgams_1_1pose_1_1Coordinate" ],
    [ "Linear", "de/d06/classgams_1_1pose_1_1Linear.html", "de/d06/classgams_1_1pose_1_1Linear" ],
    [ "LinearVector", "da/d48/classgams_1_1pose_1_1LinearVector.html", "da/d48/classgams_1_1pose_1_1LinearVector" ],
    [ "Orientation", "d4/d22/classgams_1_1pose_1_1Orientation.html", "d4/d22/classgams_1_1pose_1_1Orientation" ],
    [ "Pose", "dd/d61/classgams_1_1pose_1_1Pose.html", "dd/d61/classgams_1_1pose_1_1Pose" ],
    [ "PoseVector", "dc/ddd/classgams_1_1pose_1_1PoseVector.html", "dc/ddd/classgams_1_1pose_1_1PoseVector" ],
    [ "Position", "d6/d4a/classgams_1_1pose_1_1Position.html", "d6/d4a/classgams_1_1pose_1_1Position" ],
    [ "PrioritizedRegion", "dc/da3/classgams_1_1pose_1_1PrioritizedRegion.html", "dc/da3/classgams_1_1pose_1_1PrioritizedRegion" ],
    [ "Quaternion", "d6/d13/classgams_1_1pose_1_1Quaternion.html", "d6/d13/classgams_1_1pose_1_1Quaternion" ],
    [ "ReferenceFrame", "d3/d24/classgams_1_1pose_1_1ReferenceFrame.html", "d3/d24/classgams_1_1pose_1_1ReferenceFrame" ],
    [ "ReferenceFrameIdentity", "da/de3/classgams_1_1pose_1_1ReferenceFrameIdentity.html", "da/de3/classgams_1_1pose_1_1ReferenceFrameIdentity" ],
    [ "ReferenceFrameSettings", "da/db9/classgams_1_1pose_1_1ReferenceFrameSettings.html", "da/db9/classgams_1_1pose_1_1ReferenceFrameSettings" ],
    [ "ReferenceFrameType", "d8/d50/structgams_1_1pose_1_1ReferenceFrameType.html", "d8/d50/structgams_1_1pose_1_1ReferenceFrameType" ],
    [ "ReferenceFrameVersion", "d0/d69/classgams_1_1pose_1_1ReferenceFrameVersion.html", "d0/d69/classgams_1_1pose_1_1ReferenceFrameVersion" ],
    [ "Region", "d3/dcb/classgams_1_1pose_1_1Region.html", "d3/dcb/classgams_1_1pose_1_1Region" ],
    [ "SearchArea", "d1/d9e/classgams_1_1pose_1_1SearchArea.html", "d1/d9e/classgams_1_1pose_1_1SearchArea" ],
    [ "undefined_transform", "dd/ddd/classgams_1_1pose_1_1undefined__transform.html", "dd/ddd/classgams_1_1pose_1_1undefined__transform" ],
    [ "unrelated_frames", "dc/db8/classgams_1_1pose_1_1unrelated__frames.html", "dc/db8/classgams_1_1pose_1_1unrelated__frames" ],
    [ "Velocity", "dc/d74/classgams_1_1pose_1_1Velocity.html", "dc/d74/classgams_1_1pose_1_1Velocity" ]
];